__tests__/index.spec.js
koa/koa-reduce.js

koa compose finished by reduce api

koa compose finished by reduce api

---

__tests__/index.spec.js
koa/koa-class.js

添加compose 基于koa实现原理，利用class方式实现

add(compose-class): 添加compose 基于koa实现原理，利用class方式实现

---

chain-of-responsibility-pattern/index.js
express/index.js
koa/index.js
koa/koa-class.js
koa/koa-reduce.js
redux/reduce.js
redux/reducePromise.js
redux/reduceRight.js

- 增强 compose 函数兼容性；
- 给出参数异常提示；
- 优化代码格式。

增强 compose 函数兼容性

---

README.en-US.md
README.md

update readme file

---

__tests__/index.spec.js
async/index.js

up: async版本

---

package.json
yarn.lock

feat: 移除冗余依赖

---

__tests__/index.spec.js
generator/index.js

我是平凡的程序员，偶然间接触了开课吧，从此走向了一条不归路、
能看到这里的都是大佬，我就不说设计思路了

ES6 Generator实现责任链

---

README.en-US.md

Add: README.en-US.md

---

throttle_debounce/index.js

夏老师好!我是21期的学员舒象慧，来自深圳. 期望加入你这个造轮的项目。

---

README.md
call apply bind/README.md
call apply bind/__tests__/index.spec.js
call apply bind/index.js

[call/apply/bind 源码]

---

reactivity/vue2.js

21期学员哦，期待加入到夏老师的项目，暂时没有什么想法，还是以学习为主，后期加油争取参与到项目中。

拼写错误 修改emumerable->enumerable

---

helloworld/README.md

add ranshu to helloworld

---

helloworld/__tests__/index.spec.js
helloworld/index.js

// 1.导出一个模块
// 2.返回一个函数，函数接收一个函数参数，如果传递该参数执行之，同时传入hi给它
// 3.返回helloworld

新增了helloworld

---

00-helloworld/README.md

add mcdu11 to helloworld

---

00-helloworld/README.md

add LouieJiang to helloworld

---

00-helloworld/README.md

add dh to helloworld

---

01-material/create/__test__/index.spec.js
01-material/create/index.js

Object.create现有的对象来提供新创建的对象的__proto__,我觉得应该加上原型的测试

添加 create 测试

---

00-helloworld/README.md

add name for test

---

00-helloworld/README.md

add shadow to helloworld

---

00-helloworld/README.md

feat(README.md): 添加天才榜

---

00-helloworld/README.md

add bugLover666 to helloworld

---

00-helloworld/README.md

add Rigel to helloworld

---

01-material/compose-promise/__tests__/index.spec.js
01-material/compose-promise/index.js
01-material/compose-promise/test-case.js

promise函数的组合函数，可以让promise按照顺序任意执行，也可以混入普通的同步函数

添加promise的compose函数

---

00-helloworld/README.md

add zhiwenxuan to helloworld

---

00-helloworld/README.md

add ky6an to helloworld

---

00-helloworld/README.md

add wanggaoxian helloworld

---

00-helloworld/README.md

add CA to helloworld

---

02-part/throttle_debounce/__tests__/index.spec.js
02-part/throttle_debounce/index.js

防抖节流函数问题修复+测试用例补充

---

00-helloworld/README.md

add lczCoder to helloWorld

---

00-helloworld/README.md

feat: 新手任务

---

00-helloworld/README.md

update: add name to helloworld

---

00-helloworld/README.md

It's the first time I do the PR in this project!

add BambooSword to HelloWorld

---

00-helloworld/README.md

add yjh1342 to 00-helloworld

---

00-helloworld/README.md

add NineDays to helloworld

---

00-helloworld/README.md

zhaosasa的天才榜署名

---

00-helloworld/README.md
helloworld/__test__/index.robby.spec.js

add robby to helloworld

---

00-helloworld/README.md

add helloW

---

helloworld/index.js

add to wudexiong

---

00-helloworld/README.md

add wujq to helloworld

---

00-helloworld/README.md

add muxing123 to helloworld

---

00-helloworld/README.md

add xiaotting to helloworld

---

00-helloworld/README.md

add Zp to helloworld

---

00-helloworld/README.md

add Alwayslinzx to helloworld

---

00-helloworld/README.md

jiangjj是天才

---

00-helloworld/README.md

doc: I am a genius

---

00-helloworld/README.md

helloworld增加名字

---

01-material/sort/merge_sort/__test__/index.test.js
01-material/sort/merge_sort/index.js

feat: add merge_sort

---

00-helloworld/README.md

feat:上天才榜单【xiumubai】

---

README.md

add Ubun21 to helloworld

---

02-part/vdom/src/__tests__/diff.spec.js
03-wheel/mini-vue/runtime/diff/__tests__/index.spec.js

1、增加mini-vue diff 测试用例 
2、删除 vdom diff未引用import修复测试用例

 fix: 1、增加mini-vue diff 测试用例 2、删除vdom diff未引用import修复测试用例

---

00-helloworld/README.md

add joe to helloworld
